server:
  port: 8080
spring:
  application:
    name: template-service
  data:
    mongodb:
      user: root
      password: test123
      host: mongo
      port: 27017
      database: template
  kafka:
    bootstrap.servers: kafka:9092
    producer:
      client-id: template
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: true
      client-id: template
      group-id: template-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8095/eureka/
logging:
  level:
    com.gokhana.template: DEBUG

kafka:
  topic:
    templateEvent: templateEvent
    otherTemplate: otherTemplate