server:
  port: 8080
spring:
  application:
    name: template-service
  kafka:
    bootstrap.servers: 176.235.192.206:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: template-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8095/eureka/
logging:
  level:
    com.gokhana.template: DEBUG

kafka:
  topic:
    templateEvent: templateEvent
    otherTemplate: otherTemplate